### ISSUE TITLE
Dataset version + masks

### ISSUE THREAD

**Issue by alessiabertugli** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#18]
Hi,

Where can I find CelebaHQ dataset with the corresponding masks used for the training process (the same version you used)? I saw that the images already swapped were shared, but not the original dataset with which the train was made.

Thanks for your help

**Comment by zyainfal** [comment]
If your problem is about the inference, you can change the indexes in `face_part_ids` according to the [new version](https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing).
https://github.com/zyainfal/One-Shot-Face-Swapping-on-Megapixels/blob/edfb9c85120fb9fd32386dca1465a70694b1207c/inference/inference.py#L15
Besides, the provided masks are in 512x512, we simply resize it to 1024x1024 for inference.

And if your problem is about training, you can ignore the dataset version, because we don't need masks for training.

**Comment by zyainfal** [comment]
Well, one more thing for training, you still need [FFHQ](https://github.com/NVlabs/ffhq-dataset) and more HD training samples (by running StyleGAN version 1) as well.
And if you have real HD samples should be much better.
