### ISSUE TITLE
Swapping works but Problem at eyebrows

### ISSUE THREAD

**Issue by aravindcheruvu** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#42]
swapping of the source to target is complete. however, the swapped image is not able to remove the target image right eyebrow.
![image](https://user-images.githubusercontent.com/8363186/172014290-f204a5d5-7cfd-4cf6-aff7-dca2b5abbf36.png)
![image](https://user-images.githubusercontent.com/8363186/172014465-b81ac7c0-e589-42dc-a552-dedb868c0ca2.png)

Where is the problem in the code that I need to fix?
Appreciate your inputs!!

**Comment by zyainfal** [comment]
Only is the left eyebrow not removed. So I think the problem is that the mask you use missed it. Would you visualize the mask and check that? 
Besides, it could be also likely that the index of the left eyebrow in your mask is not in the list as in https://github.com/zyainfal/One-Shot-Face-Swapping-on-Megapixels/blob/1af90db74aeede0bb2f51175c8af957b09e38d6b/inference/inference.py#L15

**Comment by aravindcheruvu** [comment]
Thank you for the reply. I changed the face id indexes in the code and it is working now.

Thanks,
Aravind
